"""
Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


fib_seq = [1, 2]
fib_seq_even = []

while (fib_seq[-1] + fib_seq[-2]) < 4_000_000:
    fib_seq.append(fib_seq[-1] + fib_seq[-2])

for i in fib_seq:
    if i % 2 == 0:
       fib_seq_even.append(i) 

fib_seq_even_sum = sum(fib_seq_even)

print(fib_seq)
print(fib_seq_even)
print(fib_seq_even_sum)
print(len(fib_seq))
#5702886 -- 5702887
#3524576 -- 3524578
#4613732 -- 